name: Main - Build, Publish, Redeploy

on:
  push:
    branches:
    - master

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-20.04
    env:
      REPO: ${{ secrets.DOCKERHUB_REPO }}
    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} 
             -p ${{ secrets.DOCKERHUB_PASSWD }}
      - name: Build Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64 --push -t $DOCKERHUB_REPO:latest -t $DOCKERHUB_REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $DOCKERHUB_REPO

  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-20.04
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          data: "{ 'myField': 'myFieldValue'}"
